- name: "Create app folder"
  become: true
  file:
    path: /home/ubuntu/app
    state: directory

- name: "Copy backend build to server"
  become: true
  unarchive:
    src: /tmp/workspace/backend.tar.gz
    dest: /home/ubuntu/app/
    owner: ubuntu

- name: "Copy package.json to server"
  become: true
  copy:
    src: /tmp/workspace/package.json
    dest: /home/ubuntu/app/
    owner: ubuntu

- name: "Test presence of env variables"
  debug:
    msg: "TYPEORM_ENTITIES is: '{{ lookup('env', 'TYPEORM_ENTITIES') }}'"

- name: "Install backend dependencies using NPM"
  command: npm install --production
  args:
    chdir: /home/ubuntu/app

- name: "Start backend with pm2"
  become: yes
  command: pm2 start npm -- run start
#  shell: |
#    pm2 start main.js --name udapeople-backend
  args:
    chdir: /home/ubuntu/app

#- name: "Log pm2"
#  become: yes
#  shell: |
#    pm2 logs -o pm2.log --no-daemon
#    ls -la
#    cat pm2.log
#  args:
#    chdir: /home/ubuntu/app

- name: "Set pm2 start as service"
  become: yes
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup -u ubuntu
