- name: "Upgrade APT packages"
  become: true
  apt:
    upgrade: "yes"

- name: "Add nodejs APT key"
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: "Add nodejs 13.x ppa for APT repo"
  apt_repository:
    repo: deb https://deb.nodesource.com/node_13.x bionic main
    update_cache: yes

- name: "Install dependencies"
  become: true
  apt:
    name: ["nodejs", "npm"]
    update_cache: yes

- name: "Install the latest NPM version globally"
  become: true
  command: npm install -g npm

- name: "Create app folder"
  become: true
  file:
    path: /home/ubuntu/app
    state: directory

- name: "Copy backend build to server"
  become: true
  unarchive:
    src: /tmp/workspace/backend.tar.gz
    dest: /home/ubuntu/app/
    owner: ubuntu

- name: "Copy package.json to server"
  become: true
  copy:
    src: /tmp/workspace/package.json
    dest: /home/ubuntu/app/
    owner: ubuntu

- name: "Install backend dependencies using NPM"
  command: npm install
  args:
    chdir: /home/ubuntu/app

- name: "Use PM2 to run backend server"
  become: true
  command: pm2 start npm -- run "start"
  args:
    chdir: /home/ubuntu/app