- name: "Upgrade APT packages"
  become: true
  apt:
    upgrade: "yes"

- name: "Install nodejs"
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    sudo apt-get install -y nodejs

- name: "Create app folder"
  become: true
  file:
    path: /home/ubuntu/app
    state: directory

- name: "Copy backend build to server"
  become: true
  unarchive:
    src: /tmp/workspace/backend.tar.gz
    dest: /home/ubuntu/app/
    owner: ubuntu

- name: "Copy package.json to server"
  become: true
  copy:
    src: /tmp/workspace/package.json
    dest: /home/ubuntu/app/
    owner: ubuntu

- name: "Install backend dependencies using NPM"
  command: npm install
  args:
    chdir: /home/ubuntu/app

- name: "Use PM2 to run backend server"
  become: true
  command: pm2 start npm -- run "start"
  args:
    chdir: /home/ubuntu/app