- name: "Create app folder"
  become: true
  file:
    path: /home/ubuntu/app
    state: directory

- name: "Copy backend build to server"
  become: true
  unarchive:
    src: /tmp/workspace/backend.tar.gz
    dest: /home/ubuntu/app/
    owner: ubuntu

- name: "Copy package.json to server"
  become: true
  copy:
    src: /tmp/workspace/package.json
    dest: /home/ubuntu/app/
    owner: ubuntu

- name: "Install backend dependencies using NPM"
  command: npm install
  args:
    chdir: /home/ubuntu/app

- name: "Use PM2 to run backend server"
  become: true
  shell: |
    export TYPEORM_HOST="{{ lookup('env', 'TYPEORM_HOST') }}"
    export TYPEORM_ENTITIES="{{ lookup('env', 'TYPEORM_ENTITIES') }}"
    export TYPEORM_USERNAME="{{ lookup('env', 'TYPEORM_USERNAME') }}"
    export TYPEORM_PASSWORD="{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    export TYPEORM_DATABASE="{{ lookup('env', 'TYPEORM_DATABASE') }}"
    pm2 start /home/ubuntu/app/main.js --name udapeople-backend
